name: pytorch-env
channels:
- conda-forge
- bokeh
- ioam
- pytorch
dependencies:
- jupyter>=1.0
- jupyterlab=0.35.*
- matplotlib=3.0.2
- nbstripout=0.3.3
- numpy=1.15.*
- pandas=0.24.*
- python=3.6
- plotly>=2.0.5
- pytz>=2016.10
- nb_conda>=2.2
- nb_conda_kernels>=2.1
- seaborn=0.9.0
- scikit-learn=0.20.*
- fastparquet=0.1.6
- bokeh=1.0.4
- click=6.7
- pytorch=1.1.0
- pip:
  - nodejs
  - autopep8
  - jupyterlab_code_formatter
  - nbstripout
  - gpytorch